### ISSUE TITLE
Creating and Updating Sketch Styles

### ISSUE THREAD

**Issue by mpaiva** [MaxBazarov/design-system#2] opened 2019-05-21 17:10 UTC
Hi Max,
I am trying to create new styles from the JSON file, but for some reason, it is expecting the style to be already existent in the Sketch file. Is this correct? 

Also, I'd love to help you write up the documentation for this plugin, would it be okay if I fork and send you a PR?

Please let me know.
Thanks again for the contribution.

**Comment by MaxBazarov** [comment] 2019-05-23 11:24
> On 21 May 2019, at 22:40, Marcelo Paiva <notifications@github.com> wrote:
> 
> Hi Max,
> I am trying to create new styles from the JSON file, but for some reason, it is expecting the style to be already existent in the Sketch file. Is this correct?
> 

Hi,
Yes, it works by design. But I can change this design :)

I see two solutions:
1) Just skip shared style update if a layer has no such style.
2) Create new shared style automatically

What is the better from your point of view?
> Also, I'd love to help you write up the documentation for this plugin, would it be okay if I fork and send you a PR?
> 
> 

Sure! It would be great!

**Comment by mpaiva** [comment] 2019-05-23 11:51
Option 2 - creating a new style would be better, this way we can use the same JSON with other Sketch files in the project.

Let me know when you push an update and I’ll give it a try and start documenting the steps.

Thanks!

**Comment by MaxBazarov** [comment] 2019-05-23 12:10
Resolved in 1.10.0

**Closed as completed by MaxBazarov** 2019-05-23 12:10 UTC

**Comment by mpaiva** [comment] 2019-05-23 15:51
Awesome. Thanks!
